workers: 4

world_size: 1
rank: 0
dist_url: tcp://localhost:29500
dist_backend: nccl
port: 29500
node: localhost



distributed: True
seed:
gpu:
ngpu: 4
mem_gb: 128
pin_mem: True

slurm: False
slurm_suffix: ""
slurm_partition: abhinav,all
slurm_timeout: 360
nodelist: ""
exclude: ""
